### PR TITLE
Face tracking 

### PR DESCRIPTION
**Pull request by cwervo**
This begins to address #54, but fundamentally just solidifies face tracking by adding:

- fixes for glm compatibility
- adds `example-face-tracking` as a reference for an app that uses
- turns on `AR_FACE_TRACKING` by default. This is more convenient for most people just trying out functionality of the plugin, they can dig in & change the variable if they want to publish the app

Would appreciate someone just looking over the code in the example & thoughts on `AR_FACE_TRACKING` being on by default. @sortofsleepy / @aferriss ? Will merge this on July 11th if everything looks good/no one comments any issues w/ it!

### CODE REVIEW

**Comment by sortofsleepy** [comment]
Outside at the moment, so haven't really looked at the code yet but

- thanks so much for taking a look at some of the glm stuff, i had tried to
make the right changes a week or 2 ago but it broke the camera somehow.

- as far as leaving face tracking on by default, from what I understand, if
that's done, should someone want to publish on the app store, Apple will
force them to publish a privacy policy, regardless of whether or not they
actually use face tracking in their app.
That's why there are ifdef statements. I don't think turning it on by
default makes sense.

**Comment by cwervo** [comment]
- Ah, I only changed a few `ofVec2/3`s to `glm::vec2/3`s, but it's working just fine like this.
- This is really a question of what we wan the developer experience to be like, and for whom.
  - The way I see if there are two cases:
    - Developers who are **just trying out** ofxARKit & want to fiddle around with face code. These will be the vast majority & changing the flag in the plugin seems like an unnecessary burden to experimenting.
    - Developers who are **publishing to the App Story**. This is probably a small minority & in preparation for releasing an app it's relatively small for these developers to switch a flag & compile once before they submit.
  - Ultimately, whatever the choice, we just need to say, in the README & in the wiki: **Don't forget to change the boolean flag to (true|false) before releasing to the App Store.** so the choice is relatively minor, I just wanted to bring up an argument in favor of ofxARKit being as easy to get started with as possible (e.g. not having to change a flag to access a piece of the API.)

**Comment by aferriss** [comment]
Thanks for adding the example @AndresCuervo ! 

I can see both sides of the coin for leaving the tracking on / off. I'm a little biased towards leaving it off because I don't have an X to play with. However, I also think if you're about to publish an app, having to change one bool isn't much of a hassle. 

I agree that adding something to the wiki /docs informing people about the flag should happen regardless.

**Comment by ofZach** [comment]
I think anything face tracking related should be in an #ifdef so that the symbols themselves aren't compiled into your app if you don't want them.  I suspect just using a bool would still leave symbols in (this is an assumption based on this thread)

https://forum.unity.com/threads/submitting-arkit-apps-to-appstore-without-face-tracking.504572/

> "We noticed your app contains the TrueDepth APIs but we were unable to locate these features in your app. Please provide information about how your app uses the TrueDepth APIs." 

I think it's a pain enough to submit to the app store we shouldn't make it harder.    We can have the #ifdef defined (ie, face tracking code compiled by default) and include a note in the readme about submitting to the app store, ie. default to working for beginners but with easy options for more advanced users.

**Comment by cwervo** [comment]
@aferriss If you have the `AR_FACE_TRACKING` macro set to true can you still use the examples that don't involve the face stuff? If you don't have to change it then I'd be in favor of just leaving it on by default, but I'd like to know if this is the case before deciding the default for this!

@ofZach I misspoke above when I referred to it as a bool, right now the face tracking code is wrapped with an `#ifdef AR_FACE_TRACKING` so it does get removed when you set the macro to false in `ARFaceTrackingBool.h`. 

This is all valuable feedback, thanks! I think I'll take Zach's suggestion & make a README change along with this PR that points out the App Store notice.

**Comment by sortofsleepy** [comment]
Ok! finally had a moment to sit down and quick look. Code-wise looks fine. I don't see anything that looks out of place. And it sounds like most of us are in consensus of leaving it on by default but adding a note in the Readme. 

I'm honestly fine either or - it just seemed to make sense to leave it off as the X is a rather pricy device and it's not likely that a lot of people would have one. As long as the note is added I'm good.

**Comment by cwervo** [comment]
I'm switching it by default since there seems to be no harm for people without iPhone X's & it encourages ease of experimentation with the plugin. I also added a note in the README about deploying to the App Store if you're not using TrueDepth. We'll see how this goes and can change the default in the future if it proves to be a problem!

**Pull request merged**
