### PR TITLE
Fixed 'supportsFrameSemantics' error

### PR DESCRIPTION
**Pull request by sadmb**
it needs an argument so I put ARFrameSemanticSceneDepth.

related issues.
#84 #86

### CODE REVIEW

**Comment by sortofsleepy** [comment]
apologies! only just saw this, didn't get a notification for some reason, will take a look later today.

**Comment by sortofsleepy** [comment]
@sadmb as far as I can tell, looks good. Great find! I somehow missed that when first looked at the issues and could have sworn it worked previously without an argument. 

One thing though, can you close this and resubmit against `develop` instead?

**Comment by sortofsleepy** [comment]
Hi @sadmb - haven't heard from you with a re-submission in about 2 weeks according to the timestamp so I just went ahead and applied the fix in `develop`. Not sure how @ mentions work in commit messages so you might get a notification for that as well. Going to close this now. 

Appreciate the support🎉

**Comment by sadmb** [comment]
@sortofsleepy Oh, sorry I didn't noticed your reply.
Appreciate your apply. :)

**Pull request closed without merging**
