### PR TITLE
New 11.3 Features: Vertical planes, camera resolution, image recognition

### PR DESCRIPTION
**Pull request by robotconscience**
Hello!
While I don't think this is 100% complete, I wanted to see if you were interested in pulling this in so people in the #33 discussion can be somewhat satiated :)

Totally open if you think some of the APIs are weird. High-level, the changes are:
- changed 'horizontalPlane' to just 'plane' throughout
- added explicit options to just track horizontal or vertical planes
- added methods to draw the new geometry you get from plane tracking
- added a 'enableHighRes' method to configure to new 1080p default camera; setting to false finds lowest res (right now I see only 1080p and 720p on iPhone 6s + 7)
- added methods to enable image recognition (very basic!)
- added image recognition example, and quick readme how to add new images (super easy!)
- removed Xcode userdata -- now in gitignore ;)

Again, no worries if you want to just use this as a reference and roll stuff in on your own! I _think_ everything is wrapped in ```if (11.3)``` brackets, so should be non-breaking! 🤞

### CODE REVIEW

**Comment by robotconscience** [comment]
(I'm realizing this PR has a lot of un-needed commits 😬 — happy to clean up, but leaving here for you to at least check out!

**Comment by sortofsleepy** [comment]
Absolutely! This is a huge help!. 🎉 Thanks for kicking this off and getting the ball rolling. 🍻 

You actually also helped figure out a path forward into some of the image recognition stuff I had started looking into, specifically about how to declare assets. I was thinking it might be better to have an executable that could be run for larger collections of assets and knew it had to be scriptable somewhere. Now we know!

Though I don't see anything obviously wrong that might break things if I merged it in now - I'd still like to take some time to try it out. Sadly won't happen till next weekend though. If I can't get to it, I'll probably just merge it in anyways though.  And on that note - no worries about cleaning up the commits; it's great if there's time, but I'm not super anal retentive about that kinda thing. Like I said - there's really only a somewhat orderly process to this haha. 

Question though about commit b45cfe4 - nothing wrong with it, I was just curious as to why you felt planes ought to update automatically from the get go? The thinking behind leaving it off initially was to stop potential changes in lighting, tracking state, etc from changing the plane and messing up whatever visuals might be happening.

**Comment by robotconscience** [comment]
Hey hey!
1 - I think on the image recognition stuff, there's an alt / advanced version where you create them completely programmatically with a CGImage. Will try an ofImage -> CGImage -> image detection example over the coming weeks (I, too, can only work on this sporadically!)
2 - Apologies on the plane update automatically. Here's why I did it:
   - It makes the OF examples work more or less the same to Apple's example
   - It needs to happen for newer mesh / geometry stuff—which is built over time
   - The 'gotcha' for now is some cleanup needs to happen for 'dead' planes :)

All for now, cheers!

**Comment by sortofsleepy** [comment]
Ok! Tried to look at this but ... er... couldn't. No fault of your own though! Really my fault and the overly  used Macbook I was given at the place I'm at(in short it needs an OS update apparently and my user account wasn't made with admin rights; some stuff on there I'm told still needs to function, which is why I'm guessing it hasn't been updated 😞  )

That being said - trying to review this also brought up something I hadn't really considered before - the branch wouldn't build with the current release Xcode - which I guess is understandable since 11.3 is still in beta. I would have been a little hesitant anyways at merging this into `develop` as I technically still would like that branch to work for folks who don't keep up with beta releases of IOS. 

I made a `11.3` branch. When you get a sec - could you resubmit this PR against that branch instead? Sorry bout the confusion!

**Comment by robotconscience** [comment]
Hey hey! No problem. Will close this and re-open on correct branch.

I _think_ in the future, all will be in normal Xcode... I had the same issue as you, had to updated OS X alongside all fun beta-downloading on my phone. Pain!

Also also, I added a few more methods for Image Recognition, which should help in making some fun custom content. Need to debug some of the methods for tracking/updating the anchors... some weirdness there! Onwards!

**Comment by cwervo** [comment]
Hey @robotconscience any luck getting a new PR with the `11.3` branch? The changes you made look good & would like to play around with them when they make it to `master`!

**Comment by sortofsleepy** [comment]
@AndresCuervo FYI - this PR is in `develop` now and I'll be wiping the branch soon. I'm finally home and can properly test things out; so far with the exception of 2 oddly missing things and me needing to possibly rebuild all the examples, I'll merge things into master within the next couple of days once I can verify things are working with oF 0.10.0

**Comment by cwervo** [comment]
@sortofsleepy Good to hear you're back home and planning to fix/merge this soon! Out of curiosity are the "2 oddly missing things" the `updateImages()` & `getReferenceImages()` methods? I was trying to get the `example-image-recognition` from here working with `11.3`, and now `develop`, and the implementation of those methods seems to be missing. Anyway, hope you figure it out & let me know if there's anything I could do to help!

**Comment by sortofsleepy** [comment]
@AndresCuervo yup those are it. I took them out of `develop` - I only had time to do a cursory look yesterday but as far as I can tell, they were never there to begin with; that being said it's possible I messed up the merge too.

**Comment by sortofsleepy** [comment]
@AndresCuervo - ah crap - had time to look more in-depth into this and it looks like I somehow botched the merge. Gonna take me a bit longer than expected to merge things into `master` but I'm gonna be working on fixing those examples and code today.

**Comment by cwervo** [comment]
@sortasleepy — Ah okay, that must be frustrating, but at least the code's in the git history somewhere & hopefully you'll be able to resurrect a working state from fixing the merge!

**Pull request closed without merging**
